export const matadata = {
    title: "Next.js",
    describetion: "generated by Nextjs",
};
export default function ProfileLayout({
    children,
}: {        
    children: React.ReactNode;
}) {
    return (
      <html lang="en">
        <body>

          <header
            style={{
                backgroundColor: "lightgray",
                padding: "1rem",
                textAlign: "center",
            }

            }>Header</header>
          
          {children}
          <footer
          style={{
            backgroundColor: "lightgray",
            padding: "1rem",
            textAlign: "center",
        }
        }
          >Footer</footer>
        </body>
      </html>   
    );
}   