export const matadata = {
    title: "Next.js",
    describetion: "generated by Nextjs",
};
export default function ProfileLayout({
    children,
}: {        
    children: React.ReactNode;
}) {
    return (
      <html lang="en">
        <body>

          <header>Header</header>
          <h1>Profile Layout</h1>
          {children}
          <footer>Footer</footer>
        </body>
      </html>   
    );
}   